### PR TITLE
499 fix bugs that arised from changes to the performance db

### LINKED ISSUE #499: Fix bugs that arise'd from changes to the performance db
# Problem statement

the performance db has been changed, this has caused downstream bugs in our code

### PR DESCRIPTION
**Pull request by GeorgeGoodall-GovUk**
## What type of PR is this? (check all applicable)
- Bug Fix

## Description
the performance database has just been updated, this PR updates our code so it interacts with the performance db in the correct way

## Related Tickets & Documents
- Closes #499 

## QA Instructions, Screenshots, Recordings

Preview Link: https://submit-pr-504.herokuapp.com/organisations/local-authority:LBH/article-4-direction-area/overview

dataset details page working again
image

### CODE REVIEW

File: src/middleware/datasetOverview.middleware.js [hunk 1]
```diff
@@ -47,16 +47,16 @@ const fetchEntityCount = fetchOne({
 export const prepareDatasetOverviewTemplateParams = (req, res, next) => {
   const { orgInfo, specification, columnSummary, entityCount, sources, dataset } = req
 
-  const matchingFields = columnSummary[0].matching_field?.split(',') ?? []
-  const nonMatchingFields = columnSummary[0].non_matching_field?.split(',') ?? []
-  const allFields = [...matchingFields, ...nonMatchingFields]
+  const mappingFields = columnSummary[0].mapping_field?.split(';') ?? []
```
Comment (rosado) [inline src/middleware/datasetOverview.middleware.js:50]: We need a check (+ associated test case) for `columnSummary.lenght`  (`[][0]` returns `undefined` but `[][0].foo` will throw). We already have some sentry errors like this popping up (I think in the pagination code) from being a bit too optimistic about that.

**Review by rosado — CHANGES_REQUESTED** [review]

File: src/middleware/datasetOverview.middleware.js (hunk 1 above)
Comment (rosado) [reply src/middleware/datasetOverview.middleware.js:50]: If you want to handle the above in a separate PR, I'm OK with that, just to push this particular fix to prod quickly.

**Review by rosado — APPROVED** [review]

**Comment by CharliePatterson** [comment]
@GeorgeGoodall-GovUk has this been deployed? I'm still seeing the bug in production.
