### PR TITLE
check tool: display actual number of records

### LINKED ISSUE #970: [Bug 🐛] Check tool — "All data is valid" shouldn't show when there are issues
**Describe the bug**

When viewing results in the check tool the check "all data is valid" is shown despite there being issues that must be fixed.

**To Reproduce**

- Use [this endpoint](https://services7.arcgis.com/uZqSSlRPLgqdItQE/ArcGIS/rest/services/Article_4_Directions_South_Bucks/FeatureServer/0/query?where=1%3D1&f=geojson&outfields=*) in the check tool
- Click through to the results page

**Expected behavior**

The "all data is valid" check should only show if there are no issues to fix

**Screenshots / Screenrecording**

Image

**Desktop (please complete the following information):**

 - OS: mac OS
 - Browser: Firefox
 - Version: 136

### PR DESCRIPTION
**Pull request by rosado**
## Preview Link

https://submit-pr-1000.herokuapp.com/

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Bug Fix

## Description

The check tool results page currently displays only the number of records fetched for current page, not the actual number of submitted records. This PR changes it to the actual count (which is passed from the API in headers).

Also: stops displaying "All data is valid"  even when data has no records.

## Related Tickets & Documents

- Closes #970 
- Related Issue #960

## QA Instructions, Screenshots, Recordings

See [example results](https://submit-pr-1000.herokuapp.com/check/results/jLRPWuAq7YEeZCAeJnwetm/1)

## Added/updated tests?

- [x] Yes

## QA sign off
- [ ] Code has been checked and approved
- [ ] Design has been checked and approved
- [ ] Product and business logic has been checked and proved

## Summary by CodeRabbit

- **Refactor**
  - Improved the logic for calculating total rows and validating data integrity, enhancing clarity and robustness in checks.

- **Tests**
  - Added a new test suite for validating the behaviour of the checks under various conditions, including scenarios with zero and multiple records.

### CODE REVIEW

**Comment by alextea** [comment]
This looks good to me :+1:

**Review by alextea — APPROVED** [review]

**Comment by alextea** [comment]
Example with 2000 rows: https://submit.planning.data.gov.uk/check/results/Tny9MeFszr7CLAVRfsGwbv/1

File: src/controllers/resultsController.js [hunk 1]
```diff
@@ -405,30 +405,35 @@ export function getNonBlockingTasks (req, res, next) {
 }
 
 export function getPassedChecks (req, res, next) {
-  const { tasks, totalRows, missingColumnTasks } = req
```
Comment (DilwoarH) [inline src/controllers/resultsController.js:408]: where was the original `totalRows` generated? should we fix that?

**Review by DilwoarH — CHANGES_REQUESTED** [review]

File: src/controllers/resultsController.js (hunk 1 above)
Comment (rosado) [reply src/controllers/resultsController.js:408]: In `getTotalRows()` middleware. You're right, that would be better place to put that.

**Review by DilwoarH — APPROVED** [review]
Looks good to me https://submit-pr-1000.herokuapp.com/check/results/bHPJwAfqCwjPCMxx7aXxJj/1
